# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotation(object):
    def setupUi(self, annotation):
        annotation.setObjectName("annotation")
        annotation.resize(1000, 700)
        self.pushButton1 = QtWidgets.QPushButton(annotation)
        self.pushButton1.setGeometry(QtCore.QRect(850, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(annotation)
        self.pushButton2.setGeometry(QtCore.QRect(850, 130, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("background-color: rgb(80, 170, 53);")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(annotation)
        self.pushButton3.setGeometry(QtCore.QRect(850, 290, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 255);")
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(annotation)
        self.pushButton4.setGeometry(QtCore.QRect(850, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.pushButton4.setFont(font)
        self.pushButton4.setStyleSheet("background-color: rgb(80, 170, 53);")
        self.pushButton4.setObjectName("pushButton4")
        self.label = QtWidgets.QLabel(annotation)
        self.label.setGeometry(QtCore.QRect(30, 20, 800, 600))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.retranslateUi(annotation)
        QtCore.QMetaObject.connectSlotsByName(annotation)

    def retranslateUi(self, annotation):
        _translate = QtCore.QCoreApplication.translate
        annotation.setWindowTitle(_translate("annotation", "Form"))
        self.pushButton1.setText(_translate("annotation", "导入图片"))
        self.pushButton2.setText(_translate("annotation", "开始标注"))
        self.pushButton3.setText(_translate("annotation", "完成标注"))
        self.pushButton4.setText(_translate("annotation", "删除标注"))
        self.label.setText(_translate("annotation", "TextLabel"))
